[project]
name = 'pth'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-oracle-v4'
[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-storage-v4'

[contracts.callpyth]
path = 'contracts/callpyth.clar'
clarity_version = 3
epoch = '3.2'


[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'
initial_block_height = 3111111
